services:
    db:
        container_name: tanstack-router-hono-vite-starter-db
        image: postgres:16.3-alpine
        restart: always
        environment:
            - POSTGRES_PASSWORD=password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=db
        ports:
            - 5445:5432
        volumes:
            - tanstack-router-hono-vite-starter-pg-data-dev:/var/lib/postgresql/data/ # Make db data persist

volumes:
    tanstack-router-hono-vite-starter-pg-data-dev:
